title: Zhijie Liang's Homepage
page-top-title: Zhijie Liang
top-section-bg-text: Artificial Intelligence
home-subtitle: Zhijie Liang&ensp;|&ensp;梁志杰
copyright-text: '&copy; Where there is a will, there is a way.'
